src/KeepHome.Web/ViewModels/Orders/AllOrdersViewModel.cs
namespace KeepHome.Web.ViewModels.Orders
{
    using System.Collections.Generic;

    public class AllOrdersViewModel
    {
        private const string NoOrdersMessage = "Все още нямате направени поръчки.";
        public string ShowNoOrdersMessage => NoOrdersMessage;

        public IEnumerable<OrderViewModel> Orders { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Orders/ConfirmOrderViewModel.cs
namespace KeepHome.Web.ViewModels.Orders
{
    public class ConfirmOrderViewModel
    {
        public int Id { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal DeliveryPrice { get; set; }
        public string Recipient { get; set; }
        public string PhoneNumber { get; set; }

        public string DeliveryAddressOtherDetails { get; set; }
        public string DeliveryAddressStreet { get; set; }
        public string DeliveryAddressTown { get; set; }
        public string DeliveryAddressCountry { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Orders/OrderInputModel.cs
namespace KeepHome.Web.ViewModels.Orders
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using KeepHome.Models.Enums;
    using KeepHome.Web.ViewModels.Address;

    public class OrderInputModel
    {
        [Display(Name = "Адрес на получаване")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public int? DeliveryAddressId { get; set; }

        [Display(Name = "Име на получателя")]
        [Required(ErrorMessage = "Моля въведете \"{0}\".")]
        public string FullName { get; set; }

        [Display(Name = "GSM номер")]
        [Required(ErrorMessage = "Моля въведете \"{0}\".")]
        public string PhoneNumber { get; set; }

        public PaymentType PaymentType { get; set; }

        public IList<AddressInputModel> Addresses { get; set; }
        public AddressInputModel Address { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Orders/OrderViewModel.cs
namespace KeepHome.Web.ViewModels.Orders
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        public decimal TotalPrice { get; set; }
        public int Quantity { get; set; }

        public decimal ProductPrice { get; set; }
        public int ProductId { get; set; }

        public string ProductName { get; set; }
    }
}

src/KeepHome.Web/Controllers/AddressesController.cs
namespace KeepHome.Web.Controllers
{
    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels.Address;

    using Microsoft.AspNetCore.Mvc;

    public class AddressesController : BaseController
    {
        private readonly IAddressesService addressesService;

        public AddressesController(IAddressesService addressesService)
        {
            this.addressesService = addressesService;
        }

        public IActionResult Add(AddressInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.RedirectToAction("Checkout", "Orders");
            }

            var adress = this.addressesService.CreateAddress(model.Country, model.Town, model.Street, model.OtherDetails);

            this.addressesService.AddAddressToUser(this.User.Identity.Name, adress);

            return this.RedirectToAction("Checkout", "Orders");
        }
    }
}

src/KeepHome.Web/Controllers/OrdersController.cs
namespace KeepHome.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;

    using AutoMapper;

    using KeepHome.Data;
    using KeepHome.Models;
    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels.Address;
    using KeepHome.Web.ViewModels.Orders;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrdersController : BaseController
    {

        private const string ERROR_MESSAGE = "Моля добавете продукти в кошницата!";
        private const int DELIVERY_PRICE = 20;

        private readonly IAddressesService adressesService;
        private readonly IUserService userService;
        private readonly IOrderService orderService;
        private readonly IShoppingBagService shoppingBagService;
        private readonly IMapper mapper;
        private readonly IRepository<OrderProduct> orderProductRepository;

        public OrdersController(IAddressesService adressesService, IUserService userService, IOrderService orderService,
            IShoppingBagService shoppingBagService, IMapper mapper, IRepository<OrderProduct> orderProductRepository)
        {
            this.adressesService = adressesService;
            this.userService = userService;
            this.orderService = orderService;
            this.shoppingBagService = shoppingBagService;
            this.mapper = mapper;
            this.orderProductRepository = orderProductRepository;
        }

        public IActionResult Checkout()
        {
            if (!this.shoppingBagService.AnyProducts(this.User.Identity.Name))
            {
                this.TempData["error"] = ERROR_MESSAGE;
                return RedirectToAction("Index", "Home");
            }

            var order = this.orderService.CreateOrder(this.User.Identity.Name);
            var address = this.adressesService.GetAllAddressByUser(this.User.Identity.Name);

            var viewModel = this.mapper.Map<IList<AddressInputModel>>(address);

            var user = this.userService.GetUserByUsername(this.User.Identity.Name);
            var fullName = $"{user.FirstName} {user.LastName}";


            var createOrderViewModel = new OrderInputModel
            {
                Addresses = viewModel.ToList(),
                FullName = fullName,
                PhoneNumber = user.PhoneNumber
            };

            return this.View(createOrderViewModel);
        }
        
        [HttpPost]
        public IActionResult Checkout(OrderInputModel model)
        {
            if (this.ModelState.IsValid)
            {
                var order = this.orderService.GetOrderByUsername(this.User.Identity.Name);
                if (order == null)
                {
                    return this.RedirectToAction("Index", "ShoppingBag");
                }

                this.orderService.SetOrder(order, model.FullName, model.PhoneNumber, model.DeliveryAddressId.Value, DELIVERY_PRICE, model.PaymentType);

                return this.RedirectToAction(nameof(Confirm));
            }
            else
            {
                var addresses = this.adressesService.GetAllAddressByUser(this.User.Identity.Name);
                var addressesViewModel = this.mapper.Map<IList<AddressInputModel>>(addresses);

                model.Addresses = addressesViewModel.ToList();
                return this.RedirectToAction(nameof(Confirm));
            }
        }

        public IActionResult Confirm()
        {
            if (!this.shoppingBagService.AnyProducts(this.User.Identity.Name))
            {
                this.TempData["error"] = ERROR_MESSAGE;
                return RedirectToAction("Index", "Home");
            }

            var order = this.orderService.GetOrderByUsername(this.User.Identity.Name);
            var orderViewModel = new ConfirmOrderViewModel()
            {
                Id = order.Id,
                TotalPrice = order.TotalPrice,
                Recipient = order.Recipient,
                PhoneNumber = order.RecipientPhoneNumber,
                DeliveryAddressTown = order.DeliveryAddress.Town,
                DeliveryAddressStreet = order.DeliveryAddress.Street,
                DeliveryAddressCountry = order.DeliveryAddress.Country,
                DeliveryAddressOtherDetails = order.DeliveryAddress.OtherDetails,
                DeliveryPrice = DELIVERY_PRICE
            };
            return this.View(orderViewModel);
        }

        public IActionResult Finished(int id)
        {
            if (!this.shoppingBagService.AnyProducts(this.User.Identity.Name))
            {
                this.TempData["error"] = ERROR_MESSAGE;
                return RedirectToAction("Index", "Home");
            }

            var order = this.orderService.GetOrderByUsername(this.User.Identity.Name);
            this.orderService.CompleteOrder(this.User.Identity.Name);

            return this.View();
        }
        
        public IActionResult MyOrders()
        {

            var orders = this.orderProductRepository.All().Where(x => x.Order.Customer.UserName == this.User.Identity.Name)
                .Select(x => new OrderViewModel()
            {
                Id = x.OrderId,
                Quantity = x.ProductQuantity,
                TotalPrice = x.Order.TotalPrice,
                ProductName = x.ProductName,
                ProductPrice = x.Product.Price,
                ProductId = x.ProductId
            });


            var viewModel = new AllOrdersViewModel()
            {
                Orders = orders
            };

            return this.View(viewModel);
        }
    }
}

src/KeepHome.Web/Controllers/ProductsController.cs
namespace KeepHome.Web.Controllers
{
    using System.Collections.Generic;

    using AutoMapper;

    using KeepHome.Common;
    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels;
    using KeepHome.Web.ViewModels.Products;

    using Microsoft.AspNetCore.Mvc;

    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductsController(IProductService productService, IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }

        public IActionResult All(int id, int? pageNumber)
        {
            var nextPage = pageNumber ?? GlobalConstants.NextPageValue;

            var products = this.productService.GetProductsByCategory(id);

            var mappedProducts = this.mapper.Map<IEnumerable<ProductViewModel>>(products);

            var pagedProducts = mappedProducts.ToPagedList(nextPage, GlobalConstants.MaxProductsOnPage);

            var productsViewModel = new AllProductsViewModel
            {
                Products = pagedProducts
            };

            return this.View(productsViewModel);
        }

        public IActionResult Details(int id)
        {
            var product = this.productService.GetProduct(id);

            if (product == null)
            {
                return this.View("Error", new ErrorViewModel { RequestId = "Invalid product id!" });
            }

            var productViewModel = this.mapper.Map<ProductDetailsViewModel>(product);

            return this.View(productViewModel);
        }
    }
}

src/KeepHome.Web/Views/Orders/Checkout.cshtml
@model KeepHome.Web.ViewModels.Orders.OrderInputModel


<div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="width: 33%;" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100">33%</div>
</div>
<div class="h3 mt-3 mb-2">Адрес за доставка</div>
<div class="row">
    <div class="col-md-6">
        @if (Model.Addresses.Count == 0)
        {
            <p>Все още нямате добавени адреси във вашия профил.</p>
        }
            <form method="post" asp-controller="Orders" asp-action="Checkout">
                <ul class="list-group">
                    @foreach (var address in Model.Addresses)
                    {
                        <li class="list-group-item">
                            <div class="form-group border-primary mb-0">
                                <label>
                                    <input asp-for="DeliveryAddressId" type="radio" value="@address.Id" required />
                                    @address.Street, @address.Town, @address.Country,@address.OtherDetails
                                </label>
                            </div>
                        </li>
                    }
                </ul>
                <span asp-validation-for="DeliveryAddressId" class="text-danger"></span>
                <div class="text-right mt-3">
                    <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Добави нов адрес</a>
                </div>
                <div class="form-group">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" class="form-control" placeholder="Име и фамилия" required/>
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" placeholder="GSM номер" required=""/>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="h5 font-weight-bold text-center">Метод на плащане:</div>
                <div class="form-group">
                    <div>
                        <input asp-for="PaymentType" type="radio" id="Epay" value="Epay" checked>
                        <label for="Epay">ePay.bg</label>
                    </div>
                    <div>
                        <input asp-for="PaymentType" type="radio" id="Card" value="Card">
                        <label for="Card">Visa, MasterCard и др.</label>
                    </div>
                    <div>
                        <input asp-for="PaymentType" type="radio" id="EasyPay" value="EasyPay">
                        <label for="EasyPay">В брой (Изипей)</label>
                    </div>
                    <div>
                        <input asp-for="PaymentType" type="radio" id="CashОnDelivery" value="CashОnDelivery">
                        <label for="CashОnDelivery">Наложен платеж</label>
                    </div>
                </div>
                <span asp-validation-for="PaymentType" class="text-danger"></span>
                <div class="text-right mt-3 mb-3">
                    <button type="submit" class="form-group btn btn-primary btn-lg mb-0">Продължи с поръчката</button>
                </div>
            </form>
    </div>
    <div class="col-md-6">
        <div class="collapse multi-collapse" id="multiCollapseExample1">
            <div class="card card-body py-0">
                <form method="post" asp-controller="Addresses" asp-action="Add">
                    <div asp-validation-summary="All" class="text-danger mt-3"></div>
                    <div class="form-group">
                        <label asp-for="@Model.Address.Street"></label>
                        <input asp-for="@Model.Address.Street" name="Street" class="form-control" placeholder="Улица" />
                        <span asp-validation-for="@Model.Address.Street" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Address.Town"></label>
                        <input asp-for="@Model.Address.Town" name="Town" class="form-control" placeholder="Град" />
                        <span asp-validation-for="@Model.Address.Town" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Address.Country"></label>
                        <input asp-for="@Model.Address.Country" name="Country" class="form-control" placeholder="Държава" />
                        <span asp-validation-for="@Model.Address.Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Address.OtherDetails"></label>
                        <input asp-for="@Model.Address.OtherDetails" name="OtherDetails" class="form-control" placeholder="Детайли към адреса" />
                        <span asp-validation-for="@Model.Address.OtherDetails" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Добави адрес</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/KeepHome.Web/Views/Orders/Confirm.cshtml
@using KeepHome.Web.Components
@model KeepHome.Web.ViewModels.Orders.ConfirmOrderViewModel



<div class="progress mb-3 mt-4">
    <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="width: 66%;" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100">66%</div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <div><span class="font-weight-bold">Име:</span> @Model.Recipient</div>
            <hr />
            <div><span class="font-weight-bold">Телефонен номер:</span> @Model.PhoneNumber</div>
            <hr />
            <div>
                <span class="font-weight-bold">
                    Адрес:
                </span> @Model.DeliveryAddressStreet @Model.DeliveryAddressTown, @Model.DeliveryAddressCountry, @Model.DeliveryAddressOtherDetails
            </div>
            <hr />
        </div>
    </div>

    <div class="col-md-6">
        @await Component.InvokeAsync(typeof(FullShoppingBagDetailsComponent))

        @*<div class="text-center mt-4">
                <a asp-controller="Orders" asp-action="Finished" class="btn btn-danger btn-lg"><i class="fa fa-check"></i> Потвърди поръчката</a>
            </div>*@
        @await Component.InvokeAsync(typeof(PaymentOrderComponent), new { OrderId = Model.Id })

    </div>
</div>

src/KeepHome.Web/Views/Orders/Finished.cshtml
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <span class="icon-check_circle display-3 text-success"></span>
                <h2 class="display-3 text-black">Благодаря Ви!</h2>
                <p class="lead mb-5">Вашата поръчка беше направена успешно!</p>
                <p><a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-primary">Върне се към магазина</a></p>
            </div>
        </div>
    </div>
</div>

src/KeepHome.Web/Views/Orders/MyOrders.cshtml
@model KeepHome.Web.ViewModels.Orders.AllOrdersViewModel

@{
    ViewData["Title"] = "Моите поръчки";
}

<div class="mobile-fondsize-20 h2 mt-4 text-center text-info">@ViewData["Title"]</div>
<div class="container mobile-fondsize-11 mt-5">
    @if (!Model.Orders.Any())
    {
        <h2 class="text-center">@Model.ShowNoOrdersMessage</h2>
    }
    else
    {
        <table class="table table-hover">
            <thead>
                <tr class="row">
                    <th scope="col" class="col-2 d-flex justify-content-center"></th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Име на продукта</th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Количество</th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Цена</th>
                    <th scope="col" class="col-2 d-flex justify-content-center">Общо</th>
                    <th scope="col" class="col-2 d-flex justify-content-center"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model.Orders)
                {
                    <tr class="row">
                        <td class="col-2 d-flex justify-content-center"></td>
                        <td class="col-2 d-flex justify-content-center">
                            @order.ProductName
                        </td>
                        <td class="col-2 d-flex justify-content-center">
                            @order.Quantity
                        </td>
                        <td class="col-2 d-flex justify-content-center">
                            @order.ProductPrice лв.
                        </td>
                        <td class="col-2 d-flex justify-content-center">
                            @order.TotalPrice лв.
                        </td>
                        <td class="col-md-2 d-flex justify-content-around">
                            <div class="mr-2">
                                <a asp-controller="Products" asp-action="Details" asp-route-id="@order.ProductId" class="btn btn-primary btn-sm mobile-fondsize-11"> Към продукта</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>