src/KeepHome.Web/ViewModels/Home/IndexViewModel.cs
namespace KeepHome.Web.ViewModels.Home
{
    using KeepHome.Web.ViewModels.ParentCategories;
    using KeepHome.Web.ViewModels.Products;

    using System.Collections.Generic;

    public class IndexViewModel
    {
        private const string NoCategoriesMessage = "Все още няма добавени категории...";
        private const string NoLastAddedProductsMessage = "Все още няма добавени нови продукти...";

        public string ShowNoCategoriesMessage => NoCategoriesMessage;
        public string ShowNoLastAddedProductsMessage => NoLastAddedProductsMessage;

        public IEnumerable<LastAddedProductViewModel> LastAddedProducts { get; set; }
        public IEnumerable<RandomParentCategoryViewModel> RandomCategories { get; set; }
    }
}

src/KeepHome.Web/Controllers/HomeController.cs
namespace KeepHome.Web.Controllers
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;

    using AutoMapper;

    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels;
    using KeepHome.Web.ViewModels.ParentCategories;
    using KeepHome.Web.ViewModels.Products;
    using KeepHome.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private const int FeaturesProductsCount = 10;
        private const int RandomCategoriesCount = 3;

        private readonly IProductService productService;
        private readonly IParentCategoryService parentCategoryService;
        private readonly IMapper mapper;

        public HomeController(IProductService productService, IParentCategoryService parentCategoryService, IMapper mapper)
        {
            this.productService = productService;
            this.parentCategoryService = parentCategoryService;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var products = this.productService.GetAllProducts()
                               .OrderByDescending(d => d.AddedOn)
                               .Take(FeaturesProductsCount)
                               .ToList();

            var categories = this.parentCategoryService.GetCategories()
                                                       .Take(RandomCategoriesCount)
                                                       .ToList();

            var mappedProducts = this.mapper.Map<IEnumerable<LastAddedProductViewModel>>(products);
            var mappedCategories = this.mapper.Map<IEnumerable<RandomParentCategoryViewModel>>(categories);

            var indexViewModel = new IndexViewModel
            {
                LastAddedProducts = mappedProducts,
                RandomCategories = mappedCategories
            };

            return View(indexViewModel);
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/KeepHome.Web/Controllers/ParentCategoriesController.cs
namespace KeepHome.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using AutoMapper;

    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels;
    using KeepHome.Web.ViewModels.ChildCategories;
    using KeepHome.Web.ViewModels.ParentCategories;

    using Microsoft.AspNetCore.Mvc;

    public class ParentCategoriesController : BaseController
    {
        private readonly IParentCategoryService parentCategoryService;
        private readonly IChildCategoryService childCategoryService;
        private readonly IMapper mapper;

        public ParentCategoriesController(IParentCategoryService parentCategoryService, IChildCategoryService childCategoryService,
            IMapper mapper)
        {
            this.parentCategoryService = parentCategoryService;
            this.childCategoryService = childCategoryService;
            this.mapper = mapper;
        }

        public IActionResult Details(int id)
        {
            var category = this.parentCategoryService.GetCategoryById(id);

            if (category == null)
            {
                return this.View("Error", new ErrorViewModel { RequestId = "Invalid category!" });
            }

            var childCategories = category.ChildCategories;

            var childCategoriesViewModels = this.mapper.Map<IEnumerable<ChildCategoryDetailsViewModel>>(childCategories);

            var viewModel = new AllParentCategoriesDetailsViewModel
            {
                Name = category.Name,
                ChildCategories = childCategoriesViewModels
            };

            return this.View(viewModel);
        }

        public IActionResult All()
        {
            var categories = this.parentCategoryService.GetCategories();

            var categoriesViewModels = this.mapper.Map<IEnumerable<ParentCategoryViewModel>>(categories);

            var viewModel = new AllParentCategoriesViewModel
            {
                Categories = categoriesViewModels
            };

            return this.View(viewModel);
        }
    }
}

src/KeepHome.Web/Controllers/ProductsController.cs
namespace KeepHome.Web.Controllers
{
    using System.Collections.Generic;

    using AutoMapper;

    using KeepHome.Common;
    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels;
    using KeepHome.Web.ViewModels.Products;

    using Microsoft.AspNetCore.Mvc;

    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductsController(IProductService productService, IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }

        public IActionResult All(int id, int? pageNumber)
        {
            var nextPage = pageNumber ?? GlobalConstants.NextPageValue;

            var products = this.productService.GetProductsByCategory(id);

            var mappedProducts = this.mapper.Map<IEnumerable<ProductViewModel>>(products);

            var pagedProducts = mappedProducts.ToPagedList(nextPage, GlobalConstants.MaxProductsOnPage);

            var productsViewModel = new AllProductsViewModel
            {
                Products = pagedProducts
            };

            return this.View(productsViewModel);
        }

        public IActionResult Details(int id)
        {
            var product = this.productService.GetProduct(id);

            if (product == null)
            {
                return this.View("Error", new ErrorViewModel { RequestId = "Invalid product id!" });
            }

            var productViewModel = this.mapper.Map<ProductDetailsViewModel>(product);

            return this.View(productViewModel);
        }
    }
}

src/KeepHome.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "За нас";
}

<div class="container">
    <h2 class="text-center text-black">@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <hr />
    <p>
        Фирма за домашни потреби KEEPHOME е създадена през 2018 г.
        Основен приоритет на фирмата е да създава уют, хармония и красота на разумни цени, предлагайки всичко необходимо, за да бъдете "Добре дошли у дома". Обзавеждане за всички помещения, осветление и аксесоари, с които се постига необходимата завършеност и уют на дома ще впечатлят и най-претенциозните сред вас. KEEPHOME предлага широка гама от продукти и асортимент, който непрекъснато се обновява. Всички артикули са с доказано качество и произход от водещи световни и български производители.
    </p>
    <p>
        Нашата мисия е да предоставяме добри решения за организиране на един красив и приятен за живеене дом. За тази цел разполагаме със страхотен екип от професионалисти.
        Стараем се да предоставяме на клиентите си лично отношение, професионализъм и качество, обслужване от врата до врата чрез услугите транспорт, разнос и монтаж на стоките. Гордеем се с големия брой лоялни клиенти и печелим тяхното уважение с качествени и идейни продукти. Тук ще намерите голям избор от функционални предмети за бита, както и много идеи за подаръци.
        KEEPHOME е мястото, където традиционното и модерното са съчетани по неповторим начин, така че всеки да успее да създаде дома на мечтите си.
    </p>
</div>

src/KeepHome.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Контакти";
}

<div class="container">
    <h2 class="text-center text-black">@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <hr />
    <address class="text-center">
        Keep Home<br />
        София, България<br />
        <abbr title="Phone">Телефонен номер:</abbr>
        +359 884 695 169
    </address>

    <address class="text-center">
        <strong>E-mail за връзка:</strong> <a href="mailto:info@keep-home.com">info@keep-home.com</a>
    </address>
</div>

src/KeepHome.Web/Views/Home/Index.cshtml
@model KeepHome.Web.ViewModels.Home.IndexViewModel
@{
    Layout = "_Layout";
}
<div class="site-blocks-cover" style="background-image: url(images/background.png);" data-aos="fade">
    <div class="site-blocks-cover" style="background-image: url(images/dark.png);" data-aos="fade">
        <div class="site-blocks-cover" style="background-image: url(images/keephome.png);" data-aos="fade">
        </div>
    </div>
</div>

<div class="site-section site-blocks-2">
    <div class="container">
        <div class="row">
            @if (!Model.RandomCategories.Any())
            {
                <div class="col-lg-12">
                    <h2 class="text-center">@Model.ShowNoCategoriesMessage</h2>
                </div>
            }
            @foreach (var category in Model.RandomCategories)
            {
                <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                    <a class="block-2-item" asp-controller="ParentCategories" asp-action="Details" asp-route-id="@category.Id">
                        <figure class="image">
                            <img src="@category.ImageUrl" style="width:600px; height:300px" alt="" class="img-fluid">
                        </figure>
                        <div class="text">
                            <span class="text-uppercase">Категория</span>
                            <h3>@category.Name</h3>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

<div class="site-section block-3 site-blocks-2 bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7 site-section-heading text-center pt-4">
                <h2>Нови продукти</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @if (!Model.LastAddedProducts.Any())
                {
                    <h2 class="text-center">@Model.ShowNoLastAddedProductsMessage</h2>

                }
                <div class="nonloop-block-3 owl-carousel">
                    @foreach (var product in Model.LastAddedProducts)
                    {
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="@product.ImageUrl" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></h3>
                                    <p class="mb-0">Добавен на: @product.AddedOn.ToShortDateString()</p>
                                    <p class="text-primary font-weight-bold">@product.Price лв.</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>