src/KeepHome.Web/Areas/Admin/ViewModels/Products/CreateProductViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KeepHome.Web.Areas.Admin.ViewModels.Products
{
    public class CreateProductViewModel
    {
        [Display(Name = "Име на продукта")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public string Name { get; set; }

        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public decimal Price { get; set; }

        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public string Description { get; set; }
        
        [Display(Name = "Име на категория")]
        //[Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public string CategoryName { get; set; }

        [Display(Name = "Количество")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public int Quantity { get; set; }

        [Display(Name = "Снимка")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public string ImageUrl { get; set; }

        [Display(Name = "Под категория")]
        [Required(ErrorMessage = "Моля изберете \"{0}\".")]
        public int ChildCategoryId { get; set; }
        public ICollection<SelectListItem> ChildCategories { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/ViewModels/Products/EditProductViewModel.cs
namespace KeepHome.Web.Areas.Admin.ViewModels.Products
{
    public class EditProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public int ChildCategoryId { get; set; }
        public int Quantity { get; set; }
        public string CategoryName { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Products/AllProductsViewModel.cs
namespace KeepHome.Web.ViewModels.Products
{
    using System.Collections.Generic;

    public class AllProductsViewModel
    {
        private const string NoProductsMessage = "Все още няма добавени продукти...";
        public string ShowNoProductsMessage => NoProductsMessage;

        public IEnumerable<ProductViewModel> Products { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Products/LastAddedProductViewModel.cs
namespace KeepHome.Web.ViewModels.Products
{
    using System;

    public class LastAddedProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public DateTime AddedOn { get; set; }
    }
}

src/KeepHome.Web/ViewModels/Products/ProductDetailsViewModel.cs
namespace KeepHome.Web.ViewModels.Products
{
    public class ProductDetailsViewModel
    {
        private const string OutOfStockMessage = "Няма в наличност";
        private const string InStockMessage = "Наличност: {0}";

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string ImageUrl { get; set; }

        public string ShowOutOfStockMessage => OutOfStockMessage;
        public string ShowInStockMessage => string.Format(InStockMessage, this.Quantity);
    }
}

src/KeepHome.Web/ViewModels/Products/ProductViewModel.cs
namespace KeepHome.Web.ViewModels.Products
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/Controllers/ProductsController.cs
using System.Linq;
using AutoMapper;
using KeepHome.Models;
using KeepHome.Services.Contracts;
using KeepHome.Web.Areas.Admin.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KeepHome.Web.Areas.Admin.Controllers
{
    using KeepHome.Web.Areas.Admin.Controllers.Base;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : AdminBaseController
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;


        public ProductsController(IProductService productService, IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }

        public IActionResult All()
        {
            var products = this.productService.GetAllProducts();

            return View(products);
        }
        
        public IActionResult CreateProduct()
        {
            var childCategories = this.productService.GetChildCategories();

            var categories = childCategories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }).ToList();

            var model = new CreateProductViewModel { ChildCategories = categories };

            return View(model);
        }
        
        [HttpPost]
        public IActionResult CreateProduct(CreateProductViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            var product = mapper.Map<Product>(model);

            this.productService.AddProduct(product);

            return RedirectToAction(nameof(All));

        }
        
        public IActionResult Edit(int id)
        {
            var product = this.productService.GetProduct(id);

            if (product == null)
            {
                return NotFound();
            }

            var childCategories = this.productService.GetChildCategories();

            ViewData["ChildCategoryId"] = childCategories.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }).ToList();

            var model = mapper.Map<EditProductViewModel>(product);

            return View(model);
        }
        
        [HttpPost]
        public IActionResult Edit(EditProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                //TODO:Check
                var childCategories = this.productService.GetChildCategories();

                ViewData["ChildCategoryId"] = childCategories.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToList();

                return View(model);
            }

            var product = mapper.Map<Product>(model);

            this.productService.EditProduct(product);

            return RedirectToAction(nameof(All));
        }
        public IActionResult Delete(int id)
        {
            this.productService.RemoveProduct(id);
            return this.RedirectToAction(nameof(All));
        }
    }
}

src/KeepHome.Web/Controllers/ProductsController.cs
namespace KeepHome.Web.Controllers
{
    using System.Collections.Generic;

    using AutoMapper;

    using KeepHome.Common;
    using KeepHome.Services.Contracts;
    using KeepHome.Web.Controllers.Base;
    using KeepHome.Web.ViewModels;
    using KeepHome.Web.ViewModels.Products;

    using Microsoft.AspNetCore.Mvc;

    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductsController(IProductService productService, IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }

        public IActionResult All(int id, int? pageNumber)
        {
            var nextPage = pageNumber ?? GlobalConstants.NextPageValue;

            var products = this.productService.GetProductsByCategory(id);

            var mappedProducts = this.mapper.Map<IEnumerable<ProductViewModel>>(products);

            var pagedProducts = mappedProducts.ToPagedList(nextPage, GlobalConstants.MaxProductsOnPage);

            var productsViewModel = new AllProductsViewModel
            {
                Products = pagedProducts
            };

            return this.View(productsViewModel);
        }

        public IActionResult Details(int id)
        {
            var product = this.productService.GetProduct(id);

            if (product == null)
            {
                return this.View("Error", new ErrorViewModel { RequestId = "Invalid product id!" });
            }

            var productViewModel = this.mapper.Map<ProductDetailsViewModel>(product);

            return this.View(productViewModel);
        }
    }
}

src/KeepHome.Web/Controllers/ShoppingBagController.cs
using System.Linq;
using KeepHome.Services.Contracts;
using KeepHome.Web.Controllers.Base;
using KeepHome.Web.ViewModels.ShoppingBag;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KeepHome.Web.Controllers
{
    public class ShoppingBagController:BaseController
    {
        private readonly IShoppingBagService shoppingBagService;


        public ShoppingBagController(IShoppingBagService shoppingBagService)
        {
            this.shoppingBagService = shoppingBagService;
        }

        [Authorize]
        public IActionResult Index()
        {
            var shoppingBagProducts = this.shoppingBagService.GetAllShoppingBagProducts(this.User.Identity.Name);

            var viewModel = shoppingBagProducts.Select(x => new ShoppingBagProductViewModel()
            {
                Id = x.ProductId,
                Name = x.Product.Name,
                Price = x.Product.Price,
                Quantity = x.Quantity,
                TotalPrice = x.Quantity * x.Product.Price,
                ImageUrl = x.Product.ImageUrl
            });


            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Add(int id)
        {
            this.shoppingBagService.AddProduct(id, this.User.Identity.Name);
            return this.RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            this.shoppingBagService.DeleteProduct(id, this.User.Identity.Name);
            return this.RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id, int quantity)
        {
            this.shoppingBagService.EditProduct(id, this.User.Identity.Name, quantity);
            return this.RedirectToAction(nameof(Index));
        }
    }
}

src/KeepHome.Web/Views/Products/All.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model KeepHome.Web.ViewModels.Products.AllProductsViewModel

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12 order-2">
                @if (!Model.Products.Any())
                {
                    <h2 class="text-center">@Model.ShowNoProductsMessage</h2>
                }
                <div class="row mb-5">
                    @foreach (var product in Model.Products)
                    {
                        <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                            <div class="block-4 text-center border">
                                <figure class="block-4-image">
                                    <a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">
                                        <img src="@product.ImageUrl" alt="Image placeholder" class="img-fluid">
                                    </a>
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">@product.Name</a></h3>
                                    <p class="mb-0">@product.Description</p>
                                    <p class="text-primary font-weight-bold">@product.Price лв.</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="row" data-aos="fade-up">
                    <div class="col-md-12 text-center">
                        <div class="site-block-27">
                            <ul>
                                @Html.PagedListPager((IPagedList)Model.Products, pageNumber => Url.Action("All", new { pageNumber }))
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/KeepHome.Web/Views/Products/Details.cshtml
@model KeepHome.Web.ViewModels.Products.ProductDetailsViewModel

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="@Model.ImageUrl" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2 class="text-black">@Model.Name</h2>
                <p>@Model.Description</p>
                @if (Model.Quantity < 1)
                {
                    <p class="mb-4 text-danger">@Model.ShowOutOfStockMessage</p>
                }
                else
                {
                    <p class="mb-4">@Model.ShowInStockMessage</p>
                }
                <p><strong class="text-primary h4">@Model.Price лв.</strong></p>
                @if (Model.Quantity > 0)
                {
                    <p><a asp-controller="ShoppingBag" asp-action="Add" asp-route-id="@Model.Id" class="buy-now btn btn-sm btn-primary">Добави в количката</a></p>
                }
            </div>
        </div>
    </div>
</div>