src/KeepHome.Web/Areas/Admin/ViewModels/ChildCategory/AddChildCategoryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KeepHome.Web.Areas.Admin.ViewModels.ChildCategory
{
    public class AddChildCategoryViewModel
    {
        [Required(ErrorMessage = "Полето \"{0}\" e задължително.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Полето \"{0}\" трябва да бъде текст с минимална дължина {2} и максимална дължина {1} символа.")]
        [Display(Name = "Име")]
        public string Name { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Моля, изберете {0}.")]
        [Display(Name = "Основна категория")]
        public int? ParentId { get; set; }

        public ICollection<Models.ParentCategory> ParentCategories { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/ViewModels/ChildCategory/AllChildCategoryViewModel.cs
namespace KeepHome.Web.Areas.Admin.ViewModels.ChildCategory
{
    public class AllChildCategoryViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ParentCategoryName { get; set; }

        public int ProductsCount { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/ViewModels/ChildCategory/AllChildParentCategoryViewModel.cs
using System.Collections.Generic;
using KeepHome.Web.Areas.Admin.Controllers;
using KeepHome.Web.Areas.Admin.ViewModels.ParentCategory;

namespace KeepHome.Web.Areas.Admin.ViewModels.ChildCategory
{
    public class AllChildParentCategoryViewModel
    {
        public ICollection<AllChildCategoryViewModel> ChildCategoryViewModel { get; set; }

        public ICollection<ParentCategoryViewModel> ParentCategoryViewModels { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/ViewModels/ChildCategory/EditChildCategoryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KeepHome.Web.Areas.Admin.ViewModels.ChildCategory
{
    public class EditChildCategoryViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Полето \"{0}\" e задължително.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Полето \"{0}\" трябва да бъде текст с минимална дължина {2} и максимална дължина {1} символа.")]
        [Display(Name = "Име")]
        public string Name { get; set; }

        [Display(Name = "Описание")]
        public string Description { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Моля, изберете {0}.")]
        [Display(Name = "Основна категория")]
        public int? ParentCategoryId { get; set; }

        public ICollection<Models.ParentCategory> ParentCategories { get; set; }
    }
}

src/KeepHome.Web/ViewModels/ChildCategories/ChildCategoryDetailsViewModel.cs
namespace KeepHome.Web.ViewModels.ChildCategories
{
    public class ChildCategoryDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    }
}

src/KeepHome.Web/Areas/Admin/Controllers/ChildCategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using KeepHome.Common;
using KeepHome.Services.Contracts;
using KeepHome.Web.Areas.Admin.Controllers.Base;
using KeepHome.Web.Areas.Admin.ViewModels.ChildCategory;
using KeepHome.Web.Areas.Admin.ViewModels.ParentCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace KeepHome.Web.Areas.Admin.Controllers
{
    public class ChildCategoriesController:AdminBaseController
    {

        private readonly IChildCategoryService childCategoryService;
        private readonly IParentCategoryService parentCategoryService;
        private readonly IMapper mapper;

        public ChildCategoriesController(IChildCategoryService childCategoryService,
            IParentCategoryService parentCategoryService,
                                         IMapper mapper)
        {
            this.childCategoryService = childCategoryService;
            this.parentCategoryService = parentCategoryService;
            this.mapper = mapper;
        }

        public IActionResult Edit(int id)
        {
            var category = this.childCategoryService.GetChildCategoryById(id);
            var parentCategories = this.parentCategoryService.GetCategories().ToList();

            if (category == null)
            {
                return RedirectToAction(nameof(All));
            }

            var categoryViewModel = mapper.Map<EditChildCategoryViewModel>(category);
            categoryViewModel.ParentCategories = parentCategories;

            return View(categoryViewModel);
        }
        
        [HttpPost]
        public IActionResult Edit(EditChildCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ParentCategories = this.parentCategoryService.GetCategories().ToList();

                return this.View(model);
            }

            this.childCategoryService.EditChildCategory(model.Id, model.Name, (int)model.ParentCategoryId,model.ImageUrl);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Add()
        {
            var parentCategories = this.parentCategoryService.GetCategories().ToList();

            var addViewModel = new AddChildCategoryViewModel
            {
                ParentCategories = parentCategories
            };

            return View(addViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddChildCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ParentCategories = this.parentCategoryService.GetCategories().ToList();

                return this.View(model);
            }

            var childCategory = this.childCategoryService
                                    .CreateChildCategory(model.Name, (int)model.ParentId, model.ImageUrl);



            return this.RedirectToAction(nameof(All));
        }

        public IActionResult All()
        {
            var childCategories = this.childCategoryService.GetChildCategories();
            var childCategoriesViewModel = this.mapper.Map<IList<AllChildCategoryViewModel>>(childCategories);

            var parentCategories = this.parentCategoryService.GetCategories();
            var parentCategoriesViewModel = this.mapper.Map<IList<ParentCategoryViewModel>>(parentCategories);

            var childParentViewModel = new AllChildParentCategoryViewModel
            {
                ChildCategoryViewModel = childCategoriesViewModel,
                ParentCategoryViewModels = parentCategoriesViewModel
            };

            return View(childParentViewModel);
        }

        public IActionResult Delete(int id)
        {
            if (!this.childCategoryService.DeleteChildCategory(id))
            {
                this.TempData["error"] = GlobalConstants.CANNOT_DELETE_CATEGORY_IF_ANY_PRODUCTS;
            }

            return RedirectToAction(nameof(All));
        }
    }
}

src/KeepHome.Web/Areas/Admin/Views/ChildCategories/Add.cshtml
@model KeepHome.Web.Areas.Admin.ViewModels.ChildCategory.AddChildCategoryViewModel

@{
    ViewData["Title"] = "Добави под категория";
}

<div class="row">
    <div class="col-md-6">
        <section>
            <form method="post" asp-controller="ChildCategories" asp-action="Add" enctype="multipart/form-data">
                <h3 class="text-muted">@ViewData["Title"]</h3>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.Name"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.ImageUrl"></label>
                    <input asp-for="@Model.ImageUrl" class="form-control" />
                    <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <select class="select-width" name="ParentId">
                        <option value="" disabled selected>-- Основна категория --</option>
                        @if (Model.ParentCategories != null)
                        {
                            foreach (var parentCategory in Model.ParentCategories)
                            {
                                <option value="@parentCategory.Id">@parentCategory.Name</option>
                            }
                        }
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Добави</button>
                </div>
            </form>
        </section>
    </div>
</div>

src/KeepHome.Web/Areas/Admin/Views/ChildCategories/All.cshtml
@using KeepHome.Web.Areas.Admin.ViewModels.ChildCategory

@model KeepHome.Web.Areas.Admin.ViewModels.ChildCategory.AllChildParentCategoryViewModel

@{
    ViewData["Title"] = "Под категории";
}
<div class="container mobile-fondsize-11 shadow">
    <div class="mobile-fondsize-20 h3 text-muted">@ViewData["Title"]</div>
    <table class="table table-hover">
        <thead>
            <tr class="row">
                <th scope="col" class="col-lg-1 d-flex justify-content-center">Номер</th>
                <th scope="col" class="col-lg-2 d-flex justify-content-center">Име</th>
                <th scope="col" class="col-lg-3 d-flex justify-content-center">Основна категории</th>
                <th scope="col" class="col-lg-1 d-flex justify-content-center">Брой продукти</th>
                <th scope="col" class="col-lg-3 d-flex justify-content-center"><p><a asp-area="Admin" asp-controller="ChildCategories" asp-action="Add" class="btn btn-success">Създай новa под категория</a></p></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model.ChildCategoryViewModel)
            {
                <tr class="row">
                    <td class="col-1 d-flex justify-content-center">
                        @category.Id
                    </td>
                    <td class="col-2 d-flex justify-content-center">
                        @category.Name
                    </td>
                    <td class="col-3 d-flex justify-content-center">
                        @category.ParentCategoryName
                    </td>
                    <td class="col-1 d-flex justify-content-center">
                        @category.ProductsCount
                    </td>
                    <td class="col-md-3 d-flex justify-content-around">
                        <div class="mr-2">
                            <a asp-controller="ChildCategories" asp-action="Edit" asp-route-id="@category.Id" class="btn btn-sm btn-primary">Промени</a>
                        </div>
                        <div class="mr-2">
                            <a asp-controller="ChildCategories" asp-action="Delete" asp-route-id="@category.Id" class="btn btn-sm btn-outline-danger">Изтрий</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/KeepHome.Web/Areas/Admin/Views/ChildCategories/Edit.cshtml
@model KeepHome.Web.Areas.Admin.ViewModels.ChildCategory.EditChildCategoryViewModel

@{
    ViewData["Title"] = "Промени категория";
}

<div class="row">
    <div class="col-md-6">
        <section>
            <form method="post" asp-controller="ChildCategories" asp-action="Edit" enctype="multipart/form-data">
                <h3 class="mobile-fondsize-20 text-muted">@ViewData["Title"]</h3>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.Name"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.ImageUrl"></label>
                    <input asp-for="@Model.ImageUrl" class="form-control" />
                    <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <select class="select-width" name="ParentCategoryId">
                    <option value="" disabled>-- Основна категория --</option>
                    @if (Model.ParentCategories != null)
                    {
                        foreach (var category in Model.ParentCategories)
                        {
                            if (category.Id == Model.ParentCategoryId)
                            {
                                <option value="@category.Id" selected>@category.Name</option>
                            }
                            else
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        }
                    }
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Промени</button>
                </div>
            </form>
        </section>
    </div>
</div>